### ISSUE TITLE
Return also the description of the error

### ISSUE THREAD

**Issue by jmolmo** [pcuzner/ansible-runner-service#22]
https://github.com/pcuzner/ansible-runner-service/blob/2701234a8ba2fd2e902093586b2d2567e35556f3/runner_service/utils.py#L401

Is ok to log the error, but in this case:
When this function is used, for example, managing hosts, i think that to provide the description of the error to the user directly would be very useful for him.

**Comment by pcuzner** [comment]
Addressed in PR #28
