### ISSUE TITLE
Return the "public ssh key in the message"

### ISSUE THREAD

**Issue by jmolmo** [pcuzner/ansible-runner-service#23]
https://github.com/pcuzner/ansible-runner-service/blob/48ab11d1b148f73ea89aaf4722cf7b691c92b293/runner_service/utils.py#L403

If  the function ssh_connect_ok is modified to return:

- if it is possible to connect. (True.False)
- the error description if not possible.

The logic here can be simplified, and the user would get a better understanding of what is happening. ( not all the connection error cases are the same)

**Comment by pcuzner** [comment]
Should be addressed in #28
