### ISSUE TITLE
Folders in samples do not exist causing errors

### ISSUE THREAD

**Issue by Daniel-Pivonka** [pcuzner/ansible-runner-service#26]
The 'inventory' folder and the 'env' folder both do not exist when the repo is cloned. 

The first run of the service will try to create ssh keys in the 'env' folder that does not exist resulting in the error 
`runner_service.utils - ERROR - SSH setup unable to write to './samples/env/ssh_key.pub'`
manually creating the folder fixes this issue

If you try to modify the inventory without first creating the 'inventory' folder it will error 
`runner_service.utils.InventoryWriteError: Unable to create the seed inventory file at ./samples/inventory/hosts`

Both issues can be resolved by having the folders created by the service or contained in the repo.

**Comment by pcuzner** [comment]
fixed by https://github.com/pcuzner/ansible-runner-service/pull/59/commits/cd63a3249d25389e1d2687fdd4c6f941d4a16c2d in #59
