### ISSUE TITLE
Include error description

### ISSUE THREAD

**Issue by jmolmo** [pcuzner/ansible-runner-service#29]
https://github.com/pcuzner/ansible-runner-service/blob/dc248c9c3372896ea4c563ac3d9bb6fb9d6dcc39/runner_service/utils.py#L106

In generic error, to include this description is very useful. Something like:

except SSHException as ex:
logger.info ("SSH error: '{}').format(ex)

**Comment by pcuzner** [comment]
additional commit added to #28 to provide more info on exception
this particular clause has been removed, since this is on a straight file.write condition so an SSHException would not have been generated anyway
