### ISSUE TITLE
Include error description

### ISSUE THREAD

**Issue by jmolmo** [pcuzner/ansible-runner-service#30]
https://github.com/pcuzner/ansible-runner-service/blob/dc248c9c3372896ea4c563ac3d9bb6fb9d6dcc39/runner_service/utils.py#L103

Even if the error is very delimited "IOError" a brief description can help., for example, if we add the error description we will see something like:
ERROR - SSH error '[Errno 13] Permission denied: '/usr/share/ansible-runner-service/env/ssh_key.pub''

That gives us good clues about what is happening. Not only the "generic" current IOError message:

ERROR - SSH setup unable to write to '/usr/share/ansible-runner-service/env/ssh_key.pub'

**Comment by pcuzner** [comment]
Additional error handling added in commit https://github.com/pcuzner/ansible-runner-service/pull/28/commits/3f29a63a40fb3b1a747959220614444013954d98
